export const SELECT_WORKOUT_LOG_MONTH = "SELECT_WORKOUT_LOG_MONTH";
export const OPEN_WORKOUT_LOG_MODAL = "OPEN_WORKOUT_LOG_MODAL";
export const CLOSE_WORKOUT_LOG_MODAL = "CLOSE_WORKOUT_LOG_MODAL";
export const SET_SELECTED_WORKOUT_LOG = "SET_SELECTED_WORKOUT_LOG";
export const OPEN_SIDE_BAR = "OPEN_SIDE_BAR";
export const CLOSE_SIDE_BAR = "CLOSE_SIDE_BAR";
export const SELECT_DAILY_LOG_MONTH = 'SELECT_DAILY_LOG_MONTH';
