export const WRITE_DAILY_LOG = 'WRITE_DAILY_LOG';
export const WRITE_DAILY_LOGS = 'WRITE_DAILY_LOGS';
export const WRITE_DAILY_LOG_DATES = 'WRITE_DAILY_LOG_DATES';
export const DELETE_DAILY_LOG = 'DELETE_DAILY_LOG';
