export const WRITE_USER_DETAILS = "WRITE_USER_DETAILS";
export const UNSET_PICTURE = "UNSET_PICTURE";
export const WRITE_WORKOUT_TARGET = 'WRITE_WORKOUT_TARGET';
export const DELETE_WORKOUT_TARGET = 'DELETE_WORKOUT_TARGET';
