export const WRITE_WORKOUT_LOG = 'WRITE_WORKOUT_LOG';
export const WRITE_WORKOUT_LOGS = 'WRITE_WORKOUT_LOGS';
export const DELETE_WORKOUT_LOG = 'DELETE_WORKOUT_LOG';
export const WRITE_WORKOUT_LOG_DATES = 'WRITE_WORKOUT_LOG_DATES';
export const WRITE_WORKOUT_LOG_DATE = 'WRITE_WORKOUT_LOG_DATE';
export const DELETE_WORKOUT_LOG_DATE = 'DELETE_WORKOUT_LOG_DATE';
